spring:
  application:
    name: easylearn-edge
server:
  port: 8080
zuul:
  routes:
      user:
        path: /api/user/**
        serviceId: easylearn-user
      pack:
        path: /api/pack/**
        serviceId: easylearn-pack

cerberus:
  token:
    header: X-Auth-Token
    secret: sssshhhh!
    expiration: 604800

easylearn:
  testing: false

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
      enabled: true
